// DocumentFormat v2 — spec.md §31.2 (design engine v2, epic E9), ticket E9-F0a.
// Pure shared type/zod/migration; no rendering, no DB. See
// src/shared/format-v2.ts. Additive-only ticket: this file only tests the new
// module — it never touches src/shared/format.test.ts's existing coverage.
import { readFileSync } from "node:fs";
import path from "node:path";
import { describe, it, expect } from "vitest";
import {
  formatV2Schema,
  DEFAULT_FORMAT_V2,
  migrateFormat,
  isFormatV2,
  DATE_FORMATS,
  HEADING_STYLES,
  BODY_FONT_IDS,
  NAME_DISPLAY_FONT_IDS,
  CONTACT_ICON_STYLES,
  type DocumentFormatV2,
} from "@shared/format-v2";
import { DEFAULT_FORMAT } from "@shared/format";
import type { DocumentFormat } from "@shared/types";

// ── fixtures: the six retired templates' default v1 configs (templateId +
// today's DEFAULT_FORMAT fields — no other v1 field varies by template) ──
const TEMPLATE_IDS = [
  "strict",
  "classic",
  "compact",
  "banner",
  "sidebar-left",
  "sidebar-right",
] as const;

function v1Fixture(templateId: (typeof TEMPLATE_IDS)[number]): DocumentFormat {
  return { ...DEFAULT_FORMAT, templateId };
}

// Hand-authored expected v2, anchored to the ACTUAL template sources (not
// generated by running migrateFormat and pasting its output — see each
// field's comment for the source line it reproduces).
const EXPECTED_BASE: Omit<DocumentFormatV2, "layout" | "header" | "colors"> & {
  layout: DocumentFormatV2["layout"];
  header: DocumentFormatV2["header"];
  colors: DocumentFormatV2["colors"];
} = {
  formatVersion: 2,
  document: { pageFormat: "letter", dateFormat: "MM/DD/YYYY" },
  layout: {
    columns: "one",
    headerPosition: "top",
    sidebarWidthPct: 32,
    sectionPlacement: {},
    manualPageBreaks: [],
  },
  typeScale: {
    bodySize: 10, // DEFAULT_FORMAT.typography.body.size
    nameOffset: 10, // sections.tsx name fontSize is hardcoded 20; 20 - 10 = 10
    titleOffset: 0,
    sectionHeadingOffset: 1, // sections.tsx sectionLabel fontSize: body.size + 1
    entryHeaderOffset: 0, // sections.tsx groupHeading fontSize: body.size
  },
  spacing: {
    lineHeight: 1.4, // DEFAULT_FORMAT.typography.body.lineHeight
    elementSpacing: 1, // sectionGap 8pt / 6 rounded = 1
    marginsMm: { x: 14.1, y: 12.7 }, // 40pt*0.352778=14.111->14.1; 36pt*0.352778=12.700->12.7
  },
  entries: {
    structure: "full-width",
    dateLocationPlacement: "right",
    dateLocationOrder: "date-first",
    subtitlePlacement: "same-line",
    listStyle: "bullet", // sections.tsx ItemRow renders "•"
    subtitleFontStyle: "normal",
    dateFontStyle: "normal",
    locationFontStyle: "normal",
    bodyIndent: false,
  },
  headings: {
    style: "underline", // sectionLabel borderBottomWidth/borderBottomColor
    capitalization: "uppercase", // sectionLabel textTransform: "uppercase"
    icons: "none",
  },
  fonts: { body: "ibm-plex-sans", name: "same-as-body" },
  colors: {
    area: "border",
    mode: "single",
    text: "#111111", // DEFAULT_FORMAT.colors.text
    background: "#ffffff",
    accent: "#1a1a2e", // DEFAULT_FORMAT.colors.primary
    border: { size: "s", sides: { top: false, right: false, bottom: false, left: false } },
    accentPlacement: {
      name: false, // sections.tsx name color: colors.text (not primary)
      title: false,
      headings: true, // sectionLabel color: colors.primary
      headingRules: true, // sectionLabel borderBottomColor: colors.primary
      headerIcons: false,
      levelIndicators: false,
      dates: false,
      entrySubtitles: false,
      linkIcons: false,
    },
  },
  header: {
    alignment: "left",
    detailsArrangement: "stacked",
    separator: "bar",
    contactIconStyle: "none-frame",
    nameWeight: "bold", // DEFAULT_FORMAT.typography.heading.weight (600) >= 600
    titleWeight: "bold",
    titlePosition: "same-line",
  },
  photo: {
    hidden: true, // DEFAULT_FORMAT.photo.hidden
    size: 64, // DEFAULT_FORMAT.photo.size
    shape: "circle", // DEFAULT_FORMAT.photo.shape
    crop: { x: 50, y: 50 },
    zoom: 1,
  },
  links: { underline: false, accentColor: true, icon: false }, // sections.tsx link color: colors.primary
  footer: { pageNumbers: false, email: false, name: false, customText: "" },
  sectionDisplay: {
    skillsLanguages: {
      layout: "rows",
      gridColumns: 1,
      levelDisplay: "text",
      levelLabels: ["Beginner", "Elementary", "Intermediate", "Advanced", "Expert"],
    },
    interests: { layout: "rows", gridColumns: 1 },
    experience: { order: "title-first", groupPromotions: false }, // matches pre-E9 heading render (title=role leads), not the groupBy key — [v3-076]
    summary: { asPartOfHeader: false, showHeading: false }, // SummarySection renders no heading label
    education: { order: "degree-first" }, // matches pre-E9 heading render (title=degree leads) — [v3-076]
  },
};

// The retired v1 sidebar composition's own SIDEBAR_SECTIONS (deleted E9-F0d1)
const SIDEBAR_SECTIONS = ["skill", "language", "interest", "certification"];
const ALL_SECTIONS = [
  "experience",
  "project",
  "education",
  "award",
  "certification",
  "publication",
  "reference",
  "skill",
  "interest",
  "language",
];
function sidebarPlacement(): Record<string, { column: "main" | "sidebar" }> {
  const placement: Record<string, { column: "main" | "sidebar" }> = {};
  for (const section of ALL_SECTIONS) {
    placement[section] = { column: SIDEBAR_SECTIONS.includes(section) ? "sidebar" : "main" };
  }
  return placement;
}

const EXPECTED: Record<(typeof TEMPLATE_IDS)[number], DocumentFormatV2> = {
  strict: EXPECTED_BASE,
  // classic.tsx: ProfileHeader variant="centered".
  classic: { ...EXPECTED_BASE, header: { ...EXPECTED_BASE.header, alignment: "center" } },
  // compact.tsx: ProfileHeader variant="inline" (name + contact, one row).
  compact: {
    ...EXPECTED_BASE,
    header: { ...EXPECTED_BASE.header, detailsArrangement: "single-row" },
  },
  // banner.tsx: full-bleed header band filled with format.colors.primary.
  banner: { ...EXPECTED_BASE, colors: { ...EXPECTED_BASE.colors, area: "header" } },
  // sidebar.tsx: renderSidebarComposition(props, "left"); styles.sidebar width "32%".
  "sidebar-left": {
    ...EXPECTED_BASE,
    layout: {
      ...EXPECTED_BASE.layout,
      columns: "two",
      headerPosition: "left",
      sidebarWidthPct: 32,
      sectionPlacement: sidebarPlacement(),
    },
  },
  // sidebar-right.tsx: renderSidebarComposition(props, "right").
  "sidebar-right": {
    ...EXPECTED_BASE,
    layout: {
      ...EXPECTED_BASE.layout,
      columns: "two",
      headerPosition: "right",
      sidebarWidthPct: 32,
      sectionPlacement: sidebarPlacement(),
    },
  },
};

describe("migrateFormat — fixture-exact v1 -> v2 (§31.6 F0)", () => {
  for (const templateId of TEMPLATE_IDS) {
    it(`migrates the '${templateId}' default config to its exact v2 shape`, () => {
      expect(migrateFormat(v1Fixture(templateId))).toEqual(EXPECTED[templateId]);
    });
  }

  it("migrates settings.defaultFormat (== today's DEFAULT_FORMAT) to DEFAULT_FORMAT_V2", () => {
    expect(migrateFormat(DEFAULT_FORMAT)).toEqual(DEFAULT_FORMAT_V2);
  });

  it("DEFAULT_FORMAT_V2 equals the 'strict' fixture-exact expectation", () => {
    expect(DEFAULT_FORMAT_V2).toEqual(EXPECTED.strict);
  });

  it("migrates a representative lockedFormat.format snapshot the same as its live twin", () => {
    // §28.3's LockedFormat.format is just a DocumentFormat snapshot — no extra
    // shape beyond DocumentFormat, so migration is identical to the live path.
    const locked: DocumentFormat = v1Fixture("sidebar-right");
    expect(migrateFormat(locked)).toEqual(EXPECTED["sidebar-right"]);
  });
});

describe("migrateFormat — idempotence (§31.1)", () => {
  it("isFormatV2 discriminates v1 from v2", () => {
    expect(isFormatV2(DEFAULT_FORMAT)).toBe(false);
    expect(isFormatV2(DEFAULT_FORMAT_V2)).toBe(true);
    expect(isFormatV2(null)).toBe(false);
    expect(isFormatV2({})).toBe(false);
  });

  it("migrating an already-v2 value is a no-op (returns it unchanged, not re-derived)", () => {
    const once = migrateFormat(DEFAULT_FORMAT);
    // Cast mirrors a defensive runtime caller (e.g. a store that might already
    // hold a v2 value) — migrateFormat's isFormatV2 guard makes this safe.
    const twice = migrateFormat(once as unknown as DocumentFormat);
    expect(twice).toEqual(once);
    expect(twice).toBe(once); // same reference — proves it short-circuited, not re-migrated
  });
});

// [v3-044] escaped-gap repair (E9-F0d1): v1's per-section `{columns: N>1}`
// had a seam for ANY section; v2 only gives a grid axis to two display
// groups (skillsLanguages, interests, §31.2) — migrateFormat maps
// sections.skill/language.columns onto sectionDisplay.skillsLanguages
// {layout:'grid', gridColumns} and sections.interest.columns onto
// sectionDisplay.interests the same way. Consumes the pre-E9 fixtures
// VERBATIM (test/fixtures/pre-e9-formats/, forbidden to touch — read-only).
describe("migrateFormat — [v3-044] section-columns repair, over the pre-E9 fixtures verbatim", () => {
  const fixturesDir = path.join(process.cwd(), "test/fixtures/pre-e9-formats");

  it("non-empty-sections.json (sections.skill.columns:2) migrates to sectionDisplay.skillsLanguages {layout:'grid', gridColumns:2}", () => {
    const raw = JSON.parse(
      readFileSync(path.join(fixturesDir, "non-empty-sections.json"), "utf8"),
    ) as DocumentFormat;
    expect(raw.sections).toEqual({ skill: { columns: 2 } }); // fixture precondition, unchanged

    const migrated = migrateFormat(raw);
    expect(migrated.sectionDisplay.skillsLanguages.layout).toBe("grid");
    expect(migrated.sectionDisplay.skillsLanguages.gridColumns).toBe(2);
    // interests carries no v1 columns in this fixture — untouched baseline.
    expect(migrated.sectionDisplay.interests).toEqual({ layout: "rows", gridColumns: 1 });
  });

  it("non-default-photo.json (sections: {}) migrates with the baseline rows/1 sectionDisplay — no phantom grid", () => {
    const raw = JSON.parse(
      readFileSync(path.join(fixturesDir, "non-default-photo.json"), "utf8"),
    ) as DocumentFormat;
    expect(raw.sections).toEqual({});

    const migrated = migrateFormat(raw);
    expect(migrated.sectionDisplay.skillsLanguages.layout).toBe("rows");
    expect(migrated.sectionDisplay.skillsLanguages.gridColumns).toBe(1);
    expect(migrated.sectionDisplay.interests).toEqual({ layout: "rows", gridColumns: 1 });
  });

  it("non-default-photo.json (photo shown/square/non-default size) preserves the photo axes across migration", () => {
    const raw = JSON.parse(
      readFileSync(path.join(fixturesDir, "non-default-photo.json"), "utf8"),
    ) as DocumentFormat;
    expect(raw.photo).toEqual({ hidden: false, size: 96, shape: "square" });

    const migrated = migrateFormat(raw);
    expect(migrated.photo.hidden).toBe(false);
    expect(migrated.photo.shape).toBe("square");
    expect(migrated.photo.size).toBe(96);
    expect(migrated.photo.size).not.toBe(64); // distinct from the v1 default, proves it's not silently reset
  });

  it("a v1 columns:1 (no-op) never fabricates a grid layout — only columns>1 triggers the repair", () => {
    const withNoopColumns: DocumentFormat = {
      ...DEFAULT_FORMAT,
      sections: { skill: { columns: 1 }, interest: { columns: 1 } },
    };
    const migrated = migrateFormat(withNoopColumns);
    expect(migrated.sectionDisplay.skillsLanguages.layout).toBe("rows");
    expect(migrated.sectionDisplay.interests.layout).toBe("rows");
  });

  it("sections.interest.columns:3 migrates to sectionDisplay.interests {layout:'grid', gridColumns:3}, independent of skillsLanguages", () => {
    const withInterestColumns: DocumentFormat = {
      ...DEFAULT_FORMAT,
      sections: { interest: { columns: 3 } },
    };
    const migrated = migrateFormat(withInterestColumns);
    expect(migrated.sectionDisplay.interests).toEqual({ layout: "grid", gridColumns: 3 });
    expect(migrated.sectionDisplay.skillsLanguages.layout).toBe("rows");
  });
});

describe("migration anchors — named literals traceable to template source", () => {
  it("sidebar-left/right sidebarWidthPct equals the retired v1 sidebar composition's width constant (32)", () => {
    expect(migrateFormat(v1Fixture("sidebar-left")).layout.sidebarWidthPct).toBe(32);
    expect(migrateFormat(v1Fixture("sidebar-right")).layout.sidebarWidthPct).toBe(32);
  });

  it("classic maps to header.alignment 'center' (ProfileHeader variant='centered')", () => {
    expect(migrateFormat(v1Fixture("classic")).header.alignment).toBe("center");
  });

  it("compact maps to header.detailsArrangement 'single-row' (ProfileHeader variant='inline')", () => {
    expect(migrateFormat(v1Fixture("compact")).header.detailsArrangement).toBe("single-row");
  });

  it("banner maps to colors.area 'header' (full-bleed band filled with colors.primary)", () => {
    expect(migrateFormat(v1Fixture("banner")).colors.area).toBe("header");
  });

  it("sidebar-left/right assign the skill/language/interest/certification sections to the sidebar column", () => {
    const left = migrateFormat(v1Fixture("sidebar-left"));
    for (const section of SIDEBAR_SECTIONS) {
      expect(
        left.layout.sectionPlacement[section as keyof typeof left.layout.sectionPlacement],
      ).toEqual({ column: "sidebar" });
    }
    expect(left.layout.sectionPlacement.experience).toEqual({ column: "main" });
  });
});

// ── zod bounds: numeric axes ──
type Mutator = (f: DocumentFormatV2) => void;
function withMutation(mutate: Mutator): DocumentFormatV2 {
  const clone = structuredClone(DEFAULT_FORMAT_V2);
  mutate(clone);
  return clone;
}

describe("formatV2Schema — numeric bounds", () => {
  it("accepts DEFAULT_FORMAT_V2", () => {
    expect(formatV2Schema.safeParse(DEFAULT_FORMAT_V2).success).toBe(true);
  });

  const cases: { name: string; value: number; ok: boolean; mutate: Mutator }[] = [
    {
      name: "sidebarWidthPct 24 (below 25)",
      value: 24,
      ok: false,
      mutate: (f) => (f.layout.sidebarWidthPct = 24),
    },
    {
      name: "sidebarWidthPct 25 (floor)",
      value: 25,
      ok: true,
      mutate: (f) => (f.layout.sidebarWidthPct = 25),
    },
    {
      name: "sidebarWidthPct 40 (ceiling)",
      value: 40,
      ok: true,
      mutate: (f) => (f.layout.sidebarWidthPct = 40),
    },
    {
      name: "sidebarWidthPct 41 (above 40)",
      value: 41,
      ok: false,
      mutate: (f) => (f.layout.sidebarWidthPct = 41),
    },
    {
      name: "bodySize 8 (below 9)",
      value: 8,
      ok: false,
      mutate: (f) => (f.typeScale.bodySize = 8),
    },
    { name: "bodySize 9 (floor)", value: 9, ok: true, mutate: (f) => (f.typeScale.bodySize = 9) },
    {
      name: "bodySize 12 (ceiling)",
      value: 12,
      ok: true,
      mutate: (f) => (f.typeScale.bodySize = 12),
    },
    {
      name: "bodySize 13 (above 12)",
      value: 13,
      ok: false,
      mutate: (f) => (f.typeScale.bodySize = 13),
    },
    {
      name: "nameOffset 3 (below 4)",
      value: 3,
      ok: false,
      mutate: (f) => (f.typeScale.nameOffset = 3),
    },
    {
      name: "nameOffset 4 (floor)",
      value: 4,
      ok: true,
      mutate: (f) => (f.typeScale.nameOffset = 4),
    },
    {
      name: "nameOffset 12 (ceiling)",
      value: 12,
      ok: true,
      mutate: (f) => (f.typeScale.nameOffset = 12),
    },
    {
      name: "nameOffset 13 (above 12)",
      value: 13,
      ok: false,
      mutate: (f) => (f.typeScale.nameOffset = 13),
    },
    {
      name: "titleOffset -1 (below 0)",
      value: -1,
      ok: false,
      mutate: (f) => (f.typeScale.titleOffset = -1),
    },
    {
      name: "titleOffset 0 (floor)",
      value: 0,
      ok: true,
      mutate: (f) => (f.typeScale.titleOffset = 0),
    },
    {
      name: "titleOffset 4 (ceiling)",
      value: 4,
      ok: true,
      mutate: (f) => (f.typeScale.titleOffset = 4),
    },
    {
      name: "titleOffset 5 (above 4)",
      value: 5,
      ok: false,
      mutate: (f) => (f.typeScale.titleOffset = 5),
    },
    {
      name: "sectionHeadingOffset -1 (below 0)",
      value: -1,
      ok: false,
      mutate: (f) => (f.typeScale.sectionHeadingOffset = -1),
    },
    {
      name: "sectionHeadingOffset 3 (ceiling)",
      value: 3,
      ok: true,
      mutate: (f) => (f.typeScale.sectionHeadingOffset = 3),
    },
    {
      name: "sectionHeadingOffset 4 (above 3)",
      value: 4,
      ok: false,
      mutate: (f) => (f.typeScale.sectionHeadingOffset = 4),
    },
    {
      name: "entryHeaderOffset -1 (below 0)",
      value: -1,
      ok: false,
      mutate: (f) => (f.typeScale.entryHeaderOffset = -1),
    },
    {
      name: "entryHeaderOffset 2 (ceiling)",
      value: 2,
      ok: true,
      mutate: (f) => (f.typeScale.entryHeaderOffset = 2),
    },
    {
      name: "entryHeaderOffset 3 (above 2)",
      value: 3,
      ok: false,
      mutate: (f) => (f.typeScale.entryHeaderOffset = 3),
    },
    {
      name: "lineHeight 1.14 (below 1.15)",
      value: 1.14,
      ok: false,
      mutate: (f) => (f.spacing.lineHeight = 1.14),
    },
    {
      name: "lineHeight 1.5 (ceiling)",
      value: 1.5,
      ok: true,
      mutate: (f) => (f.spacing.lineHeight = 1.5),
    },
    {
      name: "lineHeight 1.51 (above 1.5)",
      value: 1.51,
      ok: false,
      mutate: (f) => (f.spacing.lineHeight = 1.51),
    },
    {
      name: "elementSpacing -1 (below 0)",
      value: -1,
      ok: false,
      mutate: (f) => (f.spacing.elementSpacing = -1),
    },
    {
      name: "elementSpacing 4 (ceiling)",
      value: 4,
      ok: true,
      mutate: (f) => (f.spacing.elementSpacing = 4),
    },
    {
      name: "elementSpacing 5 (above 4)",
      value: 5,
      ok: false,
      mutate: (f) => (f.spacing.elementSpacing = 5),
    },
    {
      name: "marginsMm.x 9 (below 10)",
      value: 9,
      ok: false,
      mutate: (f) => (f.spacing.marginsMm.x = 9),
    },
    {
      name: "marginsMm.x 28 (ceiling)",
      value: 28,
      ok: true,
      mutate: (f) => (f.spacing.marginsMm.x = 28),
    },
    {
      name: "marginsMm.x 29 (above 28)",
      value: 29,
      ok: false,
      mutate: (f) => (f.spacing.marginsMm.x = 29),
    },
    {
      name: "marginsMm.y 9 (below 10)",
      value: 9,
      ok: false,
      mutate: (f) => (f.spacing.marginsMm.y = 9),
    },
    {
      name: "marginsMm.y 28 (ceiling)",
      value: 28,
      ok: true,
      mutate: (f) => (f.spacing.marginsMm.y = 28),
    },
    {
      name: "marginsMm.y 29 (above 28)",
      value: 29,
      ok: false,
      mutate: (f) => (f.spacing.marginsMm.y = 29),
    },
    {
      name: "photo gridColumns-adjacent: skillsLanguages.gridColumns 0 (below 1)",
      value: 0,
      ok: false,
      mutate: (f) => (f.sectionDisplay.skillsLanguages.gridColumns = 0),
    },
    {
      name: "skillsLanguages.gridColumns 1 (floor)",
      value: 1,
      ok: true,
      mutate: (f) => (f.sectionDisplay.skillsLanguages.gridColumns = 1),
    },
    {
      name: "skillsLanguages.gridColumns 4 (ceiling)",
      value: 4,
      ok: true,
      mutate: (f) => (f.sectionDisplay.skillsLanguages.gridColumns = 4),
    },
    {
      name: "skillsLanguages.gridColumns 5 (above 4)",
      value: 5,
      ok: false,
      mutate: (f) => (f.sectionDisplay.skillsLanguages.gridColumns = 5),
    },
    {
      name: "interests.gridColumns 0 (below 1)",
      value: 0,
      ok: false,
      mutate: (f) => (f.sectionDisplay.interests.gridColumns = 0),
    },
    {
      name: "interests.gridColumns 4 (ceiling)",
      value: 4,
      ok: true,
      mutate: (f) => (f.sectionDisplay.interests.gridColumns = 4),
    },
    {
      name: "interests.gridColumns 5 (above 4)",
      value: 5,
      ok: false,
      mutate: (f) => (f.sectionDisplay.interests.gridColumns = 5),
    },
  ];

  for (const c of cases) {
    it(`${c.ok ? "accepts" : "rejects"} ${c.name}`, () => {
      expect(formatV2Schema.safeParse(withMutation(c.mutate)).success).toBe(c.ok);
    });
  }
});

// ── zod: enum literal sets pinned by count AND exact values ──
describe("formatV2Schema — enum literal sets (count + exact values)", () => {
  it("dateFormat has EXACTLY the 12 spec values", () => {
    expect(DATE_FORMATS.length).toBe(12);
    expect(new Set(DATE_FORMATS)).toEqual(
      new Set([
        "MM/DD/YYYY",
        "MMM DD, YYYY",
        "MMMM Do, YYYY",
        "DD/MM/YYYY",
        "DD.MM.YYYY",
        "DD MMM YYYY",
        "Do MMMM YYYY",
        "YYYY-MM-DD",
        "YYYY.MM.DD",
        "YYYY/MM/DD",
        "YYYY MMM DD",
        "YYYY MMMM DD",
      ]),
    );
  });

  it("dateFormat rejects an un-specced value ('DD-MM-YYYY')", () => {
    expect(
      formatV2Schema.safeParse(
        withMutation((f) => {
          (f.document as { dateFormat: string }).dateFormat = "DD-MM-YYYY";
        }),
      ).success,
    ).toBe(false);
  });

  it("headings.style has EXACTLY the 8 spec treatments", () => {
    expect(HEADING_STYLES.length).toBe(8);
    expect(new Set(HEADING_STYLES)).toEqual(
      new Set([
        "underline",
        "boxed",
        "outline-short-rule",
        "rules-above-below",
        "accent-bar",
        "plain",
        "thin-underline",
        "tick-marks",
      ]),
    );
  });

  it("headings.style rejects an un-specced value ('shadow')", () => {
    expect(
      formatV2Schema.safeParse(
        withMutation((f) => {
          (f.headings as { style: string }).style = "shadow";
        }),
      ).success,
    ).toBe(false);
  });

  it("header.contactIconStyle has EXACTLY the 7 spec values", () => {
    expect(CONTACT_ICON_STYLES.length).toBe(7);
    expect(new Set(CONTACT_ICON_STYLES)).toEqual(
      new Set([
        "none-frame",
        "circle-filled",
        "circle-outline",
        "rounded-filled",
        "rounded-outline",
        "square-filled",
        "square-outline",
      ]),
    );
  });

  it("colors.accentPlacement has EXACTLY 9 independent toggles", () => {
    expect(Object.keys(DEFAULT_FORMAT_V2.colors.accentPlacement).sort()).toEqual(
      [
        "name",
        "title",
        "headings",
        "headingRules",
        "headerIcons",
        "levelIndicators",
        "dates",
        "entrySubtitles",
        "linkIcons",
      ].sort(),
    );
    expect(Object.keys(DEFAULT_FORMAT_V2.colors.accentPlacement)).toHaveLength(9);
  });

  const enumCases: {
    name: string;
    count: number;
    values: string[];
    path: (f: DocumentFormatV2) => void;
    badPath: (f: DocumentFormatV2) => void;
  }[] = [
    {
      name: "entries.structure",
      count: 2,
      values: ["full-width", "columns"],
      path: (f) => (f.entries.structure = "columns"),
      badPath: (f) => ((f.entries as { structure: string }).structure = "grid"),
    },
    {
      name: "entries.dateLocationPlacement",
      count: 3,
      values: ["right", "left", "split"],
      path: (f) => (f.entries.dateLocationPlacement = "split"),
      badPath: (f) =>
        ((f.entries as { dateLocationPlacement: string }).dateLocationPlacement = "center"),
    },
    {
      name: "entries.subtitlePlacement",
      count: 2,
      values: ["same-line", "below"],
      path: (f) => (f.entries.subtitlePlacement = "below"),
      badPath: (f) => ((f.entries as { subtitlePlacement: string }).subtitlePlacement = "above"),
    },
    {
      name: "entries.listStyle",
      count: 2,
      values: ["bullet", "hyphen"],
      path: (f) => (f.entries.listStyle = "hyphen"),
      badPath: (f) => ((f.entries as { listStyle: string }).listStyle = "dash"),
    },
    {
      name: "entries.subtitleFontStyle/dateFontStyle/locationFontStyle",
      count: 3,
      values: ["normal", "bold", "italic"],
      path: (f) => (f.entries.subtitleFontStyle = "italic"),
      badPath: (f) =>
        ((f.entries as { subtitleFontStyle: string }).subtitleFontStyle = "underline"),
    },
    {
      name: "headings.capitalization",
      count: 2,
      values: ["capitalize", "uppercase"],
      path: (f) => (f.headings.capitalization = "capitalize"),
      badPath: (f) => ((f.headings as { capitalization: string }).capitalization = "lowercase"),
    },
    {
      name: "headings.icons",
      count: 3,
      values: ["none", "outline", "filled"],
      path: (f) => (f.headings.icons = "outline"),
      badPath: (f) => ((f.headings as { icons: string }).icons = "duotone"),
    },
    {
      name: "colors.area",
      count: 3,
      values: ["full-page", "header", "border"],
      path: (f) => (f.colors.area = "full-page"),
      badPath: (f) => ((f.colors as { area: string }).area = "sidebar"),
    },
    {
      name: "colors.mode",
      count: 2,
      values: ["single", "multi"],
      path: (f) => (f.colors.mode = "multi"),
      badPath: (f) => ((f.colors as { mode: string }).mode = "gradient"),
    },
    {
      name: "colors.border.size",
      count: 3,
      values: ["s", "m", "l"],
      path: (f) => (f.colors.border.size = "m"),
      badPath: (f) => ((f.colors.border as { size: string }).size = "xl"),
    },
    {
      name: "header.alignment",
      count: 2,
      values: ["left", "center"],
      path: (f) => (f.header.alignment = "center"),
      badPath: (f) => ((f.header as { alignment: string }).alignment = "right"),
    },
    {
      name: "header.detailsArrangement",
      count: 3,
      values: ["stacked", "single-row", "wrapped"],
      path: (f) => (f.header.detailsArrangement = "wrapped"),
      badPath: (f) => ((f.header as { detailsArrangement: string }).detailsArrangement = "grid"),
    },
    {
      name: "header.separator",
      count: 3,
      values: ["icon", "bullet", "bar"],
      path: (f) => (f.header.separator = "icon"),
      badPath: (f) => ((f.header as { separator: string }).separator = "dash"),
    },
    {
      name: "header.contactIconStyle",
      count: 7,
      values: [
        "none-frame",
        "circle-filled",
        "circle-outline",
        "rounded-filled",
        "rounded-outline",
        "square-filled",
        "square-outline",
      ],
      path: (f) => (f.header.contactIconStyle = "circle-filled"),
      badPath: (f) =>
        ((f.header as { contactIconStyle: string }).contactIconStyle = "triangle-filled"),
    },
    {
      name: "header.nameWeight/titleWeight",
      count: 2,
      values: ["normal", "bold"],
      path: (f) => (f.header.nameWeight = "normal"),
      badPath: (f) => ((f.header as { nameWeight: string }).nameWeight = "semibold"),
    },
    {
      name: "header.titlePosition",
      count: 2,
      values: ["same-line", "below"],
      path: (f) => (f.header.titlePosition = "below"),
      badPath: (f) => ((f.header as { titlePosition: string }).titlePosition = "above"),
    },
    {
      name: "sectionDisplay.skillsLanguages.layout",
      count: 5,
      values: ["grid", "rows", "compact", "bubble", "level"],
      path: (f) => (f.sectionDisplay.skillsLanguages.layout = "bubble"),
      badPath: (f) =>
        ((f.sectionDisplay.skillsLanguages as { layout: string }).layout = "carousel"),
    },
    {
      name: "sectionDisplay.skillsLanguages.levelDisplay",
      count: 3,
      values: ["text", "dots", "bar"],
      path: (f) => (f.sectionDisplay.skillsLanguages.levelDisplay = "dots"),
      badPath: (f) =>
        ((f.sectionDisplay.skillsLanguages as { levelDisplay: string }).levelDisplay = "stars"),
    },
  ];

  for (const c of enumCases) {
    it(`${c.name} has EXACTLY ${c.count} values: accepts a valid one, rejects an un-specced one`, () => {
      expect(c.values).toHaveLength(c.count);
      expect(formatV2Schema.safeParse(withMutation(c.path)).success).toBe(true);
      expect(formatV2Schema.safeParse(withMutation(c.badPath)).success).toBe(false);
    });
  }

  it("fonts.body has the fixed 31-face roster (§31.6 intake ledger)", () => {
    expect(BODY_FONT_IDS.length).toBe(31);
    expect(
      formatV2Schema.safeParse(withMutation((f) => (f.fonts.body = "not-a-real-font" as never)))
        .success,
    ).toBe(false);
  });

  it("fonts.name has the fixed 8-face display roster plus 'same-as-body'", () => {
    expect(NAME_DISPLAY_FONT_IDS.length).toBe(8);
    expect(
      formatV2Schema.safeParse(withMutation((f) => (f.fonts.name = "same-as-body"))).success,
    ).toBe(true);
    expect(
      formatV2Schema.safeParse(withMutation((f) => (f.fonts.name = "comic-sans" as never))).success,
    ).toBe(false);
  });

  it("interests.layout has exactly 4 values (skillsLanguages' 5 minus 'level')", () => {
    expect(
      formatV2Schema.safeParse(
        withMutation((f) => (f.sectionDisplay.interests.layout = "level" as never)),
      ).success,
    ).toBe(false);
  });
});

// ── zod: rejects an object missing each top-level group ──
describe("formatV2Schema — rejects a value missing each top-level group", () => {
  const groups = [
    "document",
    "layout",
    "typeScale",
    "spacing",
    "entries",
    "headings",
    "fonts",
    "colors",
    "header",
    "photo",
    "links",
    "footer",
    "sectionDisplay",
  ] as const;

  for (const group of groups) {
    it(`rejects a value missing '${group}'`, () => {
      const broken = structuredClone(DEFAULT_FORMAT_V2) as Record<string, unknown>;
      delete broken[group];
      expect(formatV2Schema.safeParse(broken).success).toBe(false);
    });
  }

  it("rejects a value missing formatVersion", () => {
    const broken = structuredClone(DEFAULT_FORMAT_V2) as Record<string, unknown>;
    delete broken.formatVersion;
    expect(formatV2Schema.safeParse(broken).success).toBe(false);
  });
});

describe("formatV2Schema — hex colors and footer text", () => {
  it("rejects a malformed accent hex ('#zzz')", () => {
    expect(formatV2Schema.safeParse(withMutation((f) => (f.colors.accent = "#zzz"))).success).toBe(
      false,
    );
  });

  it("rejects a footer customText containing a newline", () => {
    expect(
      formatV2Schema.safeParse(withMutation((f) => (f.footer.customText = "line one\nline two")))
        .success,
    ).toBe(false);
  });

  it("accepts a one-line footer customText", () => {
    expect(
      formatV2Schema.safeParse(withMutation((f) => (f.footer.customText = "Confidential"))).success,
    ).toBe(true);
  });
});

describe("presetId — provenance only", () => {
  it("is optional and accepted when present", () => {
    expect(
      formatV2Schema.safeParse(withMutation((f) => (f.presetId = "classic-preset"))).success,
    ).toBe(true);
  });

  it("DEFAULT_FORMAT_V2 carries no presetId (not derived from a saved preset)", () => {
    expect(DEFAULT_FORMAT_V2.presetId).toBeUndefined();
  });
});
