// A fake `claude` binary for tests that drive ClaudeCliEngine.
//
// Not a spec file (vitest's default include only collects *.test.*/*.spec.*)
// and never wired into any config — each test that wants it imports it,
// prepends the stub dir to PATH, and restores PATH itself.
//
// PREPENDING IS MANDATORY, not hygiene: this dev container ships a REAL
// `claude` on PATH, so a test that merely hoped the binary was absent would
// spend a real subscription call. Symmetrically, "binary missing" is always
// produced by REPLACING PATH with a claude-free directory
// (`pathWithoutClaude()`), never by assuming absence.
//
// The stub records every invocation to a JSONL file BEFORE it acts, so even
// the mode that never returns is observable.

import { chmodSync, existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";

export type StubRecord = {
  pid: number;
  argv: string[];
  stdin: string;
  cwd: string;
  cwdEntries: string[];
  env: Record<string, string>;
  // The `--system-prompt-file` the engine wrote, captured while it still
  // exists — the engine deletes its scratch dir on every path, so this is the
  // only window in which the file the CLI was actually handed is readable.
  systemPrompt: string | null;
};

export type ClaudeStub = {
  dir: string;
  recordPath: string;
  readRecords: () => StubRecord[];
  cleanup: () => void;
};

// Temp dirs handed out by pathWithoutClaude(); drained by the stub's
// cleanup() so the helper as a whole leaves nothing behind.
const claudeFreeDirs: string[] = [];

export function installClaudeStub(): ClaudeStub {
  const dir = mkdtempSync(path.join(os.tmpdir(), "lede-claude-stub-"));
  const binPath = path.join(dir, "claude");
  const recordPath = path.join(dir, "records.jsonl");

  writeFileSync(binPath, STUB_SCRIPT, "utf-8");
  chmodSync(binPath, 0o755);

  return {
    dir,
    recordPath,
    readRecords: () => {
      if (!existsSync(recordPath)) return [];
      return readFileSync(recordPath, "utf-8")
        .split("\n")
        .filter((line) => line.length > 0)
        .map((line) => JSON.parse(line) as StubRecord);
    },
    cleanup: () => {
      rmSync(dir, { recursive: true, force: true });
      while (claudeFreeDirs.length > 0) {
        rmSync(claudeFreeDirs.pop() as string, { recursive: true, force: true });
      }
    },
  };
}

export function pathWithStub(stubDir: string): string {
  return `${stubDir}${path.delimiter}${process.env.PATH}`;
}

export function pathWithoutClaude(): string {
  const dir = mkdtempSync(path.join(os.tmpdir(), "lede-no-claude-"));
  claudeFreeDirs.push(dir);
  return dir;
}

// Behaviour is chosen entirely by env (LEDE_STUB_MODE / LEDE_STUB_PAYLOAD /
// LEDE_STUB_RECORD) so one written binary serves every scenario — and so the
// engine's env inheritance is what makes the stub work at all.
//
// `library-derived` reads the system prompt back and answers from it: one item
// per rendered entry, text = that entry's first fact, rank counted per
// section, leadRationale everywhere, empty cut, digit-free summary. That
// combination survives validateDecisionContract, validateNoFabrication and
// validateLedeRationale for an arbitrary seeded library, so route- and
// e2e-level tests get a real decision without a real model.
const STUB_SCRIPT = `#!/usr/bin/env node
"use strict";
// Generated by test/helpers/claude-stub.ts. Do not edit; it lives in a temp dir.
const fs = require("node:fs");

const argv = process.argv.slice(2);

function flagValue(name) {
  const i = argv.indexOf(name);
  return i >= 0 ? argv[i + 1] : undefined;
}

let stdin = "";
try {
  stdin = fs.readFileSync(0, "utf-8");
} catch (err) {
  stdin = "";
}

const systemPromptFile = flagValue("--system-prompt-file");
let systemPrompt = null;
if (systemPromptFile) {
  try {
    systemPrompt = fs.readFileSync(systemPromptFile, "utf-8");
  } catch (err) {
    systemPrompt = null;
  }
}

const recordPath = process.env.LEDE_STUB_RECORD;
fs.appendFileSync(
  recordPath,
  JSON.stringify({
    pid: process.pid,
    argv: argv,
    stdin: stdin,
    cwd: process.cwd(),
    cwdEntries: fs.readdirSync(process.cwd()),
    env: Object.assign({}, process.env),
    systemPrompt: systemPrompt,
  }) + "\\n",
);

const invocation = fs
  .readFileSync(recordPath, "utf-8")
  .split("\\n")
  .filter(function (line) {
    return line.length > 0;
  }).length;

function payloadText() {
  return fs.readFileSync(process.env.LEDE_STUB_PAYLOAD, "utf-8");
}

function emit(resultText, isError) {
  process.stdout.write(
    JSON.stringify({
      result: resultText,
      is_error: Boolean(isError),
      subtype: isError ? "error_during_execution" : "success",
    }),
  );
  process.exit(0);
}

function deriveDecision(systemText) {
  const lines = systemText.split("\\n");
  const items = [];
  const rankBySection = {};
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (line.charAt(0) !== "[") continue;
    const close = line.indexOf("] ");
    if (close < 1) continue;
    if ((lines[i + 1] || "").indexOf("context: ") !== 0) continue;
    const section = line.slice(1, close);
    const id = line.slice(close + 2).trim();
    let fact = "";
    for (let j = i + 1; j < lines.length; j++) {
      if (lines[j] !== "facts:") continue;
      const next = lines[j + 1] || "";
      if (next.indexOf("  - ") === 0) fact = next.slice(4);
      break;
    }
    rankBySection[section] = (rankBySection[section] || 0) + 1;
    items.push({
      entryId: id,
      text: fact,
      rank: rankBySection[section],
      leadRationale: "leads on the stub's deterministic library order",
    });
  }
  return {
    signals: {
      roleLevel: "stub",
      weights: ["stub weighting"],
      hardRequirements: ["stub requirement"],
    },
    summary: "Stub-derived summary carrying no numerals at all.",
    items: items,
    cut: [],
  };
}

const mode = process.env.LEDE_STUB_MODE || "ok";

if (mode === "hang") {
  setTimeout(function () {}, 600000);
} else if (mode === "exit1") {
  process.stderr.write("stub: simulated non-zero exit\\n");
  process.exit(1);
} else if (mode === "echo-env-stderr-exit1") {
  process.stderr.write(JSON.stringify(process.env) + "\\n");
  process.exit(1);
} else if (mode === "prose") {
  process.stdout.write("Here is my take on the role, in plain prose.\\n");
  process.exit(0);
} else if (mode === "is-error") {
  emit("the stub was told to report a failed result", true);
} else if (mode === "is-error-once") {
  if (invocation <= 1) emit("the stub fails its first invocation by design", true);
  emit(payloadText(), false);
} else if (mode === "schema-invalid") {
  emit('{"lead": 42}', false);
} else if (mode === "ok-fenced") {
  emit("\`\`\`json\\n" + payloadText() + "\\n\`\`\`", false);
} else if (mode === "library-derived") {
  emit(JSON.stringify(deriveDecision(systemPrompt || "")), false);
} else {
  emit(payloadText(), false);
}
`;
